// eslint-disable-next-line import/no-anonymous-default-export
export default [
  {
    login: "Katiao",
    id: 59416030,
    node_id: "MDQ6VXNlcjU5NDE2MDMw",
    avatar_url: "https://avatars.githubusercontent.com/u/59416030?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Katiao",
    html_url: "https://github.com/Katiao",
    followers_url: "https://api.github.com/users/Katiao/followers",
    following_url: "https://api.github.com/users/Katiao/following{/other_user}",
    gists_url: "https://api.github.com/users/Katiao/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Katiao/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Katiao/subscriptions",
    organizations_url: "https://api.github.com/users/Katiao/orgs",
    repos_url: "https://api.github.com/users/Katiao/repos",
    events_url: "https://api.github.com/users/Katiao/events{/privacy}",
    received_events_url: "https://api.github.com/users/Katiao/received_events",
    type: "User",
    site_admin: false,
    name: "Katia ",
    company: null,
    blog: "https://www.katiaouahes.com/",
    location: "Munich, Germany",
    email: null,
    hireable: true,
    bio: null,
    twitter_username: null,
    public_repos: 8,
    public_gists: 0,
    followers: 2,
    following: 1,
    created_at: "2020-01-01T15:42:42Z",
    updated_at: "2021-06-26T20:29:48Z",
  },
  {
    login: "john-smilga",
    id: 42133389,
    node_id: "MDQ6VXNlcjQyMTMzMzg5",
    avatar_url: "https://avatars.githubusercontent.com/u/42133389?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/john-smilga",
    html_url: "https://github.com/john-smilga",
    followers_url: "https://api.github.com/users/john-smilga/followers",
    following_url:
      "https://api.github.com/users/john-smilga/following{/other_user}",
    gists_url: "https://api.github.com/users/john-smilga/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/john-smilga/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/john-smilga/subscriptions",
    organizations_url: "https://api.github.com/users/john-smilga/orgs",
    repos_url: "https://api.github.com/users/john-smilga/repos",
    events_url: "https://api.github.com/users/john-smilga/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/john-smilga/received_events",
    type: "User",
    site_admin: false,
    name: "John Smilga",
    company: "Coding Addict",
    blog: "www.johnsmilga.com",
    location: "Los Angeles",
    email: null,
    hireable: null,
    bio: "Creator of Coding Addict",
    twitter_username: "john_smilga",
    public_repos: 213,
    public_gists: 0,
    followers: 5874,
    following: 0,
    created_at: "2018-08-06T06:48:23Z",
    updated_at: "2021-06-25T04:06:34Z",
  },
  {
    login: "bradtraversy",
    id: 5550850,
    node_id: "MDQ6VXNlcjU1NTA4NTA=",
    avatar_url: "https://avatars.githubusercontent.com/u/5550850?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/bradtraversy",
    html_url: "https://github.com/bradtraversy",
    followers_url: "https://api.github.com/users/bradtraversy/followers",
    following_url:
      "https://api.github.com/users/bradtraversy/following{/other_user}",
    gists_url: "https://api.github.com/users/bradtraversy/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/bradtraversy/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/bradtraversy/subscriptions",
    organizations_url: "https://api.github.com/users/bradtraversy/orgs",
    repos_url: "https://api.github.com/users/bradtraversy/repos",
    events_url: "https://api.github.com/users/bradtraversy/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/bradtraversy/received_events",
    type: "User",
    site_admin: false,
    name: "Brad Traversy",
    company: "Traversy Media",
    blog: "traversymedia.com",
    location: "Massachusetts",
    email: null,
    hireable: true,
    bio: "Full stack web developer and online instructor, specializiing in mostly JS, but also write Python, PHP and some other stuff.",
    twitter_username: "traversymedia",
    public_repos: 224,
    public_gists: 37,
    followers: 41416,
    following: 6,
    created_at: "2013-09-26T15:36:02Z",
    updated_at: "2021-07-01T17:04:47Z",
  },
];
