// eslint-disable-next-line import/no-anonymous-default-export
export default {
  login: "Katiao",
  id: 59416030,
  node_id: "MDQ6VXNlcjU5NDE2MDMw",
  avatar_url: "https://avatars.githubusercontent.com/u/59416030?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Katiao",
  html_url: "https://github.com/Katiao",
  followers_url: "https://api.github.com/users/Katiao/followers",
  following_url: "https://api.github.com/users/Katiao/following{/other_user}",
  gists_url: "https://api.github.com/users/Katiao/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Katiao/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Katiao/subscriptions",
  organizations_url: "https://api.github.com/users/Katiao/orgs",
  repos_url: "https://api.github.com/users/Katiao/repos",
  events_url: "https://api.github.com/users/Katiao/events{/privacy}",
  received_events_url: "https://api.github.com/users/Katiao/received_events",
  type: "User",
  site_admin: false,
  name: "Katia ",
  company: null,
  blog: "https://www.katiaouahes.com/",
  location: "Munich, Germany",
  email: null,
  hireable: true,
  bio: null,
  twitter_username: null,
  public_repos: 8,
  public_gists: 0,
  followers: 2,
  following: 1,
  created_at: "2020-01-01T15:42:42Z",
  updated_at: "2021-06-26T20:29:48Z",
};
